/**
 * File generated by Magnet rest2mobile 1.1 - Apr 20, 2015 5:27:02 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.cted.barcodereader.controller.api.test;

import android.test.InstrumentationTestCase;
import android.test.suitebuilder.annotation.SmallTest;
import android.test.suitebuilder.annotation.Suppress;

import com.magnet.android.mms.MagnetMobileClient;
import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.exception.SchemaException;
import java.util.concurrent.ExecutionException;

import com.example.cted.barcodereader.controller.api.SendQrCodeToServer;
import com.example.cted.barcodereader.controller.api.SendQrCodeToServerFactory;

/**
* This is generated stub to test {@link SendQrCodeToServer}
* <p>
* All test cases are suppressed by defaullt. To run the test, you need to fix all the FIXMEs first :
* <ul>
* <li>Set proper value for the parameters
* <li>Remove out the @Suppress annotation
* <li>(optional)Add more asserts for the result
* <ul><p>
*/

public class SendQrCodeToServerTest extends InstrumentationTestCase {
  private SendQrCodeToServer sendQrCodeToServer;

  @Override
  protected void setUp() throws Exception {
    super.setUp();

    // Instantiate a controller
    MagnetMobileClient magnetClient = MagnetMobileClient.getInstance(this.getInstrumentation().getTargetContext());
    SendQrCodeToServerFactory controllerFactory = new SendQrCodeToServerFactory(magnetClient);
    sendQrCodeToServer = controllerFactory.obtainInstance();

    assertNotNull(sendQrCodeToServer);
  }

  /**
    * Generated unit test for {@link SendQrCodeToServer#qrCodeSend}
    */
  @Suppress //FIXME : set proper parameter value and un-suppress this test case
  @SmallTest
  public void testQrCodeSend() throws SchemaException, ExecutionException, InterruptedException {
    // FIXME : set proper value for the parameters
    String userId = null;
    String qrCode = null;
    String barcodereaderApi = null;

    Call<Void> callObject = sendQrCodeToServer.qrCodeSend(
      userId, 
      qrCode, 
      barcodereaderApi, null);
    assertNotNull(callObject);

    Void result = callObject.get();
    
    //TODO : add more asserts
  }

}
