/**
 * File generated by Magnet rest2mobile 1.1 - Apr 20, 2015 5:27:02 PM
 * @see {@link http://developer.magnet.com}
 */

package com.example.cted.barcodereader.controller.api;

import com.magnet.android.mms.async.Call;
import com.magnet.android.mms.async.StateChangedListener;


public interface SendQrCodeToServer {

  /**
   * Generated from URL POST http://gemroc-dev.gemroc.com/qrCode/send?userId=654897787re3&qrCode=911200AB
   * POST qrCode/send
   * @param userId  style:QUERY
   * @param qrCode  style:QUERY
   * @param barcodereaderApi (original name : barcodereader-api) style:HEADER
   * @param listener
   * @return void
   */
  Call<Void> qrCodeSend(
     String userId,
     String qrCode,
     String barcodereaderApi,
     StateChangedListener listener
  );


}
